import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import './globals.css'
import { Users } from 'lucide-react'
import { Toaster } from '@/components/ui/toaster'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {



  return (
    //@ts-ignore
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16 min-w-full ">
            <nav className=" min-w-full border-b border-border bg-card/50 backdrop-blur-sm">
              <div className=" mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between items-center h-16">
                  <div className="flex items-center gap-2">
                    <Link href="/" className='flex items-center gap-2'>
                      <div className="w-8 h-8 bg-primary rounded-full flex items-center justify-center">
                        <Users className="w-5 h-5 text-primary-foreground" />
                      </div>
                      <span className="text-xl font-bold text-foreground">Mesh</span>
                    </Link>

                  </div>
                  <div className="flex-grow flex items-center justify-center gap-3">
                    <Link href="/event" className=''>
                      <Button variant="outline" size="sm">
                        Events
                      </Button>
                    </Link>
                    <Link href="/dashboard">
                      <Button variant="outline" size="sm">
                        Dashboard
                      </Button>
                    </Link>
                    <Link href="/lookout">
                      <Button variant="outline" size="sm">
                        Opportunities
                      </Button>
                    </Link>
                  </div>
                  <div className="flex items-center gap-4">
                    {/* @ts-ignore */}
                    <SignedOut>
                      <SignInButton>
                        <div className="text-white px-6 cursor-pointer rounded-full py-2 bg-primary hover:bg-transparent hover:text-primary hover:border-primary border border-primary transition-all duration-300">
                          Sign In
                        </div>
                      </SignInButton>
                      {/* <SignUpButton>
                        <div className="text-white px-6 cursor-pointer rounded-full py-2 bg-primary hover:bg-transparent hover:text-primary hover:border-primary border border-primary transition-all duration-300">
                          Sign Up
                        </div>
                      </SignUpButton> */}
                    </SignedOut>
                    {/* @ts-ignore */}
                    <SignedIn>
                      <UserButton />
                    </SignedIn>
                  </div>
                </div>
              </div>
            </nav>
          </header>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}